CREATE GLOBAL TEMPORARY TABLE IMPORTACODBARRAS(
            CODPROD NUMBER,
            CODBARRAS VARCHAR2(100)
        )
        ON COMMIT DELETE ROWS;
/* *** */
select COUNT(*) from IMPORTACODBARRAS;
/* *** */
DECLARE
    CONTACODIGO NUMBER;
    PARAMETRO NUMBER;
    RESULTB NUMBER := 0;
    RESULTI NUMBER := 0;
    RESULTD NUMBER := 0;
    RESULTJ NUMBER := 0;
    RESULTK NUMBER := 0;
    RESULTU NUMBER := 0;
BEGIN
    FOR I IN (SELECT * FROM TGFPRO)
    LOOP
        BEGIN
            SELECT COUNT(*)
              INTO CONTACODIGO
              FROM IMPORTACODBARRAS
             WHERE CODPROD = I.CODPROD;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            CONTACODIGO := 0;
        END;
        
        IF CONTACODIGO = 0 THEN
            INSERT INTO TGFBAR (CODBARRA, CODPROD, DHALTER, CODUSU, CODVOL)
                VALUES(I.CODPROD, I.CODPROD, SYSDATE, 15, I.CODVOL);
            RESULTB := RESULTB + 1;
        END IF;
        
        FOR J IN (SELECT * FROM IMPORTACODBARRAS WHERE CODPROD = I.CODPROD)
        LOOP
            FOR K IN 1..CONTACODIGO
            LOOP
                IF K = 1 THEN
                    DBMS_OUTPUT.PUT_LINE(J.CODBARRAS);
                    UPDATE TGFPRO SET REFERENCIA = J.CODBARRAS
                     WHERE CODPROD = I.CODPROD;
                    RESULTU := RESULTU + 1; 
                ELSIF K >= 2 THEN
                    BEGIN
                        SELECT COUNT(CODBARRA)
                          INTO PARAMETRO
                          FROM TGFBAR
                         WHERE CODPROD = I.CODPROD
                           AND CODBARRA = J.CODBARRAS;
                    EXCEPTION WHEN NO_DATA_FOUND THEN
                        PARAMETRO := 0; 
                    END;
                      
                    IF PARAMETRO = 0 THEN
                        INSERT INTO TGFBAR (CODBARRA, CODPROD, DHALTER, CODUSU, CODVOL)
                            VALUES(J.CODBARRAS, I.CODPROD, SYSDATE, 15, I.CODVOL);
                        RESULTK := RESULTK + 1;
                    END IF;
                END IF;
            END LOOP;  
            RESULTJ := RESULTJ + 1;  
        END LOOP;
        RESULTI := RESULTI + 1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('TOTAL DE PRODUTOS: '||RESULTI);
    DBMS_OUTPUT.PUT_LINE('TOTAL DE CODBARRAS: '||RESULTJ);
    DBMS_OUTPUT.PUT_LINE('TOTAL DE INSER��ES: '||RESULTK);
    DBMS_OUTPUT.PUT_LINE('TOTAL DE UPDATES: '||RESULTU);
    DBMS_OUTPUT.PUT_LINE('TOTAL S/ C�DIGO: '||RESULTB);
    FOR I IN (SELECT * FROM TGFPRO WHERE REFERENCIA IS NOT NULL)
    LOOP
        FOR J IN (SELECT * FROM TGFBAR WHERE CODPROD = I.CODPROD)
        LOOP
            DBMS_OUTPUT.PUT_LINE(J.codbarra);
            DBMS_OUTPUT.PUT_LINE(I .referencia);
            IF J.CODBARRA = I.REFERENCIA THEN
                DELETE FROM TGFBAR WHERE CODPROD = I.CODPROD AND CODBARRA = I.REFERENCIA;
            END IF;
            RESULTD := RESULTD + 1;
        END LOOP;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('TOTAL DELETADOS (C�DIGO REPETIDO!!!): '||RESULTD);

    EXECUTE IMMEDIATE 'DELETE FROM IMPORTACODBARRAS';     
    EXECUTE IMMEDIATE 'DROP TABLE IMPORTACODBARRAS';
    COMMIT;
END;
/
/* *** */