BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE TMDFMD DISABLE CONSTRAINT FK_TMDFMD_CODFILA_TMDFMG';
    DELETE FROM TMDAXM;
    DELETE FROM TMDAMG;
    DELETE FROM TMDFMG;
    DELETE FROM TMDFMD;
    DELETE FROM AD_AVISARECEB;
    DELETE FROM AD_CHAMADOSTI;
    DELETE FROM AD_CONTATOLIBCOMP;
    DELETE FROM AD_CONTGARITE;
    DELETE FROM AD_CONTGARCAB;
    DELETE FROM AD_CONTSERV;
    DELETE FROM AD_COTFRETEVOL;
    DELETE FROM AD_COTFRETECAB;
    DELETE FROM AD_DESCQTD;
    DELETE FROM AD_GONDOLETIQ;
    DELETE FROM AD_IMPTABRES;
    DELETE FROM AD_IMPTABITE;
    DELETE FROM AD_IMPTAB;
    DELETE FROM AD_PENDPARC;
    DELETE FROM AD_PROITE;
    DELETE FROM AD_PROMO;
    DELETE FROM AD_REFERCOM;
    DELETE FROM AD_TABENC;
    DELETE FROM AD_PRODTICHAMADO;
    EXECUTE IMMEDIATE 'ALTER TABLE TMDFMD ENABLE CONSTRAINT FK_TMDFMD_CODFILA_TMDFMG';
END;
/
