DECLARE
  TEXTO VARCHAR2(4000);
BEGIN
  FOR I IN 1..4
  LOOP
    IF I = 1 THEN
      TEXTO := 'ALTER TRIGGER TRG_DLT_TGFTAB DISABLE';
    ELSIF I = 2 THEN  
      TEXTO := 'ALTER TRIGGER TRG_DLT_TGFTAB_AFTER DISABLE';
    ELSIF I = 3 THEN
      TEXTO := 'ALTER TABLE TGFTAB MODIFY CONSTRAINT FK_TGFTAB_CODTAB_TGFNTA DISABLE';
    ELSIF I = 4 THEN
      TEXTO := 'ALTER TABLE TGFTAB MODIFY CONSTRAINT FK_TGFTAB_CODTABORIG_TGFNTA DISABLE';
    ELSIF I = 5 THEN
      TEXTO := 'ALTER TABLE TGFPAEM MODIFY CONSTRAINT FK_TGFPAEM_CODTAB_TGFNTA ENABLE';
    END IF;
    
    EXECUTE IMMEDIATE TEXTO;
  END LOOP;
  
  DELETE FROM TGFPAEM;
  DELETE FROM TGFTAB; 
  DELETE FROM TGFNTA WHERE CODTAB > 0;
  
  FOR I IN 1..4
  LOOP
    IF I = 1 THEN
      TEXTO := 'ALTER TABLE TGFTAB MODIFY CONSTRAINT FK_TGFTAB_CODTABORIG_TGFNTA ENABLE';
    ELSIF I = 2 THEN
      TEXTO := 'ALTER TABLE TGFTAB MODIFY CONSTRAINT FK_TGFTAB_CODTAB_TGFNTA ENABLE';  
    ELSIF I = 3 THEN
      TEXTO := 'ALTER TRIGGER TRG_DLT_TGFTAB_AFTER ENABLE';
    ELSIF I = 4 THEN
      TEXTO := 'ALTER TRIGGER TRG_DLT_TGFTAB ENABLE';
    ELSIF I = 5 THEN
      TEXTO := 'ALTER TABLE TGFPAEM MODIFY CONSTRAINT FK_TGFPAEM_CODTAB_TGFNTA ENABLE';
    END IF;
      
    EXECUTE IMMEDIATE TEXTO;
  END LOOP;
END;
/
