ALTER TRIGGER TRG_DLT_TGFTAB DISABLE;
ALTER TRIGGER TRG_DLT_TGFTAB_AFTER DISABLE;
ALTER TABLE TGFTAB MODIFY CONSTRAINT FK_TGFTAB_CODTAB_TGFNTA DISABLE;
ALTER TABLE TGFTAB MODIFY CONSTRAINT FK_TGFTAB_CODTABORIG_TGFNTA DISABLE;

DELETE FROM TGFTAB;
DELETE FROM TGFNTA WHERE CODTAB > 0;
SELECT * FROM TGFTAB;

ALTER TABLE TGFTAB MODIFY CONSTRAINT FK_TGFTAB_CODTABORIG_TGFNTA ENABLE;
ALTER TABLE TGFTAB MODIFY CONSTRAINT FK_TGFTAB_CODTAB_TGFNTA ENABLE;
ALTER TRIGGER TRG_DLT_TGFTAB_AFTER ENABLE;
ALTER TRIGGER TRG_DLT_TGFTAB ENABLE;