/****************************************** DELETANDO PRODUTOS ******************************************/
/* DESATIVANDO TRIGGER */
ALTER TRIGGER TRG_BLQALTERITC_COT_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_INS_PRODOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_INS_SERVOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_UPD_PRODOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_UPD_SERVOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_PRODOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_SERVOS_JGD DISABLE;
ALTER TRIGGER TRG_DLT_TCIBEM DISABLE;
ALTER TRIGGER TRG_DLT_AD_IMPTABITE_JGD DISABLE;
ALTER TRIGGER TRG_DLT_UPD_TGFCUS DISABLE;
ALTER TRIGGER TRG_DLT_TGFITE DISABLE;
ALTER TRIGGER TRG_DLT_TGFITS DISABLE;
ALTER TRIGGER TRG_INC_UPD_DLT_TGFITE_RASTEST DISABLE;
ALTER TRIGGER TRG_INC_UPD_DLT_TGFITE_ESTTERC DISABLE;
ALTER TRIGGER TRG_DLT_TCIMOV DISABLE;
ALTER TRIGGER TRG_DLT_TCIBEM DISABLE;
ALTER TRIGGER TRG_DLT_TCISAL DISABLE;
/* FIM DE BLOCO */
/* DESABILITAR CONSTRAINT'S */
--FK_TCIMOV_CODBEM_TCIBEM;
--FK_TCISAL_CODBEM_TCIBEM;
--FK_TCICTA_CODPROD_TCIBEM;
--FK_TCICTA_CODPROD_TGFPRO;
--FK_TCITAX_CODBEM_TCIBEM;
--FK_TCITAX_CODPROD_TGFPRO;
--FK_TCIEST_CODPROD_TGFPRO;
--FK_TCIDIBI_CODPROD_TGFPRO;
--FK_TCIDIBI_CODBEM_TCIBEM;
/* FIM DO BLOCO */
/* DELETAR PRODUTOS */
BEGIN
    FOR I IN (SELECT CODPROD FROM TGFPRO)
    LOOP
        DELETE FROM TGFIMAL         WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFFAM          WHERE CODPRODPAI = I.CODPROD OR CODPRODFILHO = I.CODPROD;
        DELETE FROM TGFVCS          WHERE CODPRODSUG = I.CODPROD;
        DELETE FROM TCIBEM          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFPAP          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFEXC          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFITC          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFBAR          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFEST          WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_CONTGARITE   WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_AVISARECEB   WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_CENTPARAMPRO WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_DESCQTD      WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_GONDOLETIQ   WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_IMPTABITE    WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_IMPTABRES    WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_PRODCODNVL   WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_PRODOS       WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_PROITE       WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_RECEBETIQ    WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_SERVOS       WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_TABENC       WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFITS          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFCUS          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFITC_COT      WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFITC          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFITE          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFCOI2         WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFGIR1         WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFVOA          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFIRCST        WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFIVC          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFCTE          WHERE CODPROD    = I.CODPROD;        
        DELETE FROM TGFAID          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TCIDIBI         WHERE CODPROD    = I.CODPROD;
        DELETE FROM TCILOC          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TCIEST          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TCICTA          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TCIBEM          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TCISAL          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TCIMOV          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TCITAX          WHERE CODPROD    = I.CODPROD;
        DELETE FROM TGFPRO          WHERE CODPROD    = I.CODPROD;
        DELETE FROM AD_FABRICANTES  WHERE CODFAB NOT IN (SELECT AD_CODFAB FROM TGFPRO);
    END LOOP;
END;
/* FIM DO BLOCO */
/* REATIVANDO TRIGGERS */
ALTER TRIGGER TRG_BLQALTERITC_COT_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_INS_PRODOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_INS_SERVOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_UPD_PRODOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_UPD_SERVOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_PRODOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_SERVOS_JGD ENABLE;
ALTER TRIGGER TRG_DLT_AD_IMPTABITE_JGD ENABLE;
ALTER TRIGGER TRG_INC_UPD_DLT_TGFITE_ESTTERC ENABLE;
ALTER TRIGGER TRG_INC_UPD_DLT_TGFITE_RASTEST ENABLE;
ALTER TRIGGER TRG_DLT_TGFITS ENABLE;
ALTER TRIGGER TRG_DLT_TGFITE ENABLE;
ALTER TRIGGER TRG_DLT_UPD_TGFCUS ENABLE;
ALTER TRIGGER TRG_DLT_TCIBEM ENABLE;
ALTER TRIGGER TRG_DLT_TCIMOV ENABLE;
ALTER TRIGGER TRG_DLT_TCIBEM ENABLE;
ALTER TRIGGER TRG_DLT_TCISAL ENABLE;
/* FIM DO BLOCO */
/**************************************************FIM!**************************************************/