/* AREA PARA DESATIVAR TRIGGERS */
ALTER TRIGGER TRG_DLT_TGFMBC DISABLE;
ALTER TRIGGER TRG_DLT_TGFFIN DISABLE;
ALTER TRIGGER TRG_DLT_TGFFRE DISABLE;
ALTER TRIGGER TRG_DLT_TGFRAT DISABLE;
ALTER TRIGGER TRG_BLQ_INS_PRODOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_INS_SERVOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_UPD_PRODOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_UPD_SERVOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_UPD_ORDSERV_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_PRODOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_SERVOS_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_ORDSERV_JGD DISABLE;
/* FIM DO BLOCO*/
/* Constraints */
'FK_TGFFIN_TGFMBC'
'FK_TGFCAB_NUREM_TGFCAB'
'CKC_TGFCAB_EXC_TGFCAB'
'FK_TGFCAB_TGFCON2'
/* FIM DO BLOCO
/* DELETAR NOTAS/PARCEIROS */
BEGIN
    DELETE FROM TGFMBC;
    DELETE FROM TGFREN;
    DELETE FROM TGFFRE;
    DELETE FROM AD_INTDDA;
    DELETE FROM AD_INTCARTAO;
    DELETE FROM AD_IMPTABITE;
    DELETE FROM AD_IMPTAB;
    DELETE FROM AD_IMPTABRES;
    DELETE FROM TCBINT;
    DELETE FROM TCIDIB;
    DELETE FROM TGFACF;
    DELETE FROM TGFFNF;
    DELETE FROM AD_COTFRETEVOL;
    DELETE FROM TGFRAT;
    DELETE FROM TGFCON2;
    DELETE FROM TGFFIN;
    DELETE FROM TGFITE_EXC;
    DELETE FROM TGFCAB_EXC;
    FOR I IN (SELECT NUNOTA FROM TGFCAB WHERE TIPMOV != 'Z' OR NUNOTA NOT IN (4,62,64,65,75,79,99,208,243,295,439,1023,4025,4388,4409,4410,6774))
    LOOP 
        DELETE FROM TCBINT WHERE NUNICO = I.NUNOTA;
        DELETE FROM AD_VOLS WHERE NUNOTA = I.NUNOTA;
        DELETE FROM AD_CONTGARCAB WHERE NUNOTA = I.NUNOTA;
        DELETE FROM AD_AVISARECEB WHERE NUNOTA = I.NUNOTA;
        DELETE FROM AD_TABENC WHERE NUNOTA = I.NUNOTA;
        DELETE FROM AD_SERVOS WHERE NOTAGERADA = I.NUNOTA;
        DELETE FROM AD_PRODOS WHERE NOTAGERADA = I.NUNOTA;
        DELETE FROM AD_ORDSERV WHERE NOTGERNF = I.NUNOTA OR NOTGERNFS = I.NUNOTA;
        DELETE FROM AD_VOLUMENTREG WHERE NUNOTA = I.NUNOTA;
        DELETE FROM AD_PENDPARC WHERE NUNOTA = I.NUNOTA;
        DELETE FROM AD_COTFRETECAB WHERE NUNOTA = I.NUNOTA;
        DELETE FROM TGFVAR WHERE NUNOTA = I.NUNOTA OR NUNOTAORIG = I.NUNOTA;
        DELETE FROM TGFFIN WHERE NUNOTA = I.NUNOTA;    
        DELETE FROM TGFLIV WHERE NUNOTA = I.NUNOTA;
        DELETE FROM TGFCAB WHERE NUNOTA = I.NUNOTA;
    END LOOP;
END;
/
/* FIM DO BLOCO */
/* AREA PARA ATIVAR TRIGGERS */
ALTER TRIGGER TRG_DLT_TGFMBC ENABLE;
ALTER TRIGGER TRG_DLT_TGFFIN ENABLE;
ALTER TRIGGER TRG_DLT_TGFFRE ENABLE;
ALTER TRIGGER TRG_DLT_TGFRAT ENABLE;
ALTER TRIGGER TRG_BLQ_INS_PRODOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_INS_SERVOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_UPD_PRODOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_UPD_SERVOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_UPD_ORDSERV_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_PRODOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_SERVOS_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_ORDSERV_JGD ENABLE;
/* FIM DO BLOCO*/