/* DESATIVAR TRIGGERS */
ALTER TRIGGER TRG_BLQ_UPD_ORDSERV_JGD DISABLE;
ALTER TRIGGER TRG_BLQ_ORDSERV_JGD DISABLE;
/* FIM DO BLOCO */
/* CONSTRAINTS */
/* FIM DO BLOCO */
/* DELETANDO PARCEIROS */
BEGIN
    UPDATE TSIUSU SET CODPARC = 0;
    DELETE FROM TGFGIR;
    DELETE FROM TGFTEL;
    DELETE FROM AD_ORDSERV;
    DELETE FROM TGFLIS;
    DELETE FROM AD_PENDPARC;
    DELETE FROM AD_CONTATOLIBCOMP;
    DELETE FROM TGFORD;
    FOR I IN (SELECT CODPARC FROM TGFPAR WHERE CODPARC NOT IN (SELECT CODPARC FROM TSIEMP))
    LOOP
        IF I.CODPARC NOT IN (0, 18, 50, 53, 75, 96) THEN
            DELETE FROM TGFPAR WHERE CODPARC = I.CODPARC;
        END IF;
    END LOOP;
END;
/* FIM DO BLOCO */
/* ATIVANDO TRIGGERS */
ALTER TRIGGER TRG_BLQ_UPD_ORDSERV_JGD ENABLE;
ALTER TRIGGER TRG_BLQ_ORDSERV_JGD ENABLE;
/* FIM DO BLOCO */
/* ALTERAR PARCEIROS DA EMPRESA */
BEGIN
    UPDATE TGFCAB SET CODPARC = 0 WHERE CODPARC != 0;
    UPDATE TGFPAR SET CODPARCMATRIZ = 0 WHERE CODPARC != 0;
    UPDATE TGFPAR SET CODPARC = 1 WHERE CODPARC = 9;
    UPDATE TSIEMP SET CODPARC = 0 WHERE CODPARC != 0;
    UPDATE TGFEMP SET CODPARCNFCE = 0 WHERE CODPARCNFCE != 0;
    UPDATE TGFPAR SET CODPARC = 109 WHERE CODPARC = 2;
    UPDATE TGFPAR SET CODPARC = CODPARC - 8 WHERE CODPARC IN (10, 11);
    UPDATE TGFCAB SET CODPARC = 1 WHERE NUNOTA = 6774;
    UPDATE TGFPAR SET CODPARCMATRIZ = CODPARC WHERE CODPARC IN (1, 2, 3);
    UPDATE TSIEMP SET CODPARC = CODEMP;
    UPDATE TGFPAR SET CODPARC = 9 WHERE CODPARC = 109;
    UPDATE TGFPAR SET CODPARC = 10 WHERE CODPARC = 96;
    UPDATE TGFEMP SET CODPARCNFCE = 9;
END;
/* FIM DO BLOCO */
/* TOPPERSON'S DELETEIDES */
ALTER TRIGGER TRG_DLT_TGFTOP DISABLE;
DELETE FROM TGFTOP_DLT WHERE CODTIPOPER = 9994;
DELETE FROM TGFTOP WHERE CODTIPOPER = 9994;
ALTER TRIGGER TRG_DLT_TGFTOP ENABLE;
COMMIT;
/* FIM DO BLOCO */
