CREATE TABLE IMPORT_CUSTO(
    CODPROD         NUMBER,
    CODEMP          NUMBER,
    DTATUAL         DATE,
    CODLOCAL        NUMBER,
    CONTROLE        VARCHAR2(2),
    CUSREP          FLOAT(126),
    CURVARIAVEL     FLOAT(126),
    NUNOTA          NUMBER
);
DECLARE
    ERRO       VARCHAR2(4000);
    PARAMETRO          NUMBER;
    CONTADOR           NUMBER := 0;
    CONTAGEM           NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO CONTAGEM
      FROM IMPORT_CUSTO;
      
    FOR I IN(SELECT * FROM IMPORT_CUSTO WHERE CODPROD IN (SELECT CODPROD FROM TGFPRO))
    LOOP
            INSERT INTO TGFCUS (CODPROD, CODEMP, DTATUAL, CODLOCAL, CONTROLE,
                    CUSREP, CUSVARIAVEL, NUNOTA)
                VALUES(I.CODPROD, I.CODEMP, I.DTATUAL, I.CODLOCAL,
                    NVL(I.CONTROLE, ' '), I.CUSREP, I.CURVARIAVEL, I.NUNOTA);
            CONTADOR := CONTADOR + 1;   
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE(CONTADOR);
    DBMS_OUTPUT.PUT_LINE(CONTAGEM);

    EXECUTE IMMEDIATE 'DELETE FROM IMPORT_CUSTO; IMPORT_CUSTO;';
END;
/

DELETE FROM IMPORT_CUSTO;
DROP TABLE IMPORT_CUSTO;