/* Cria tabela de IMPORT CUSTOS */
CREATE TABLE IMPORT_CUSTO(
    CODPROD NUMBER(10),
    DTATUAL DATE,
    CUSVARIAVEL FLOAT(126),
    CUSREP FLOAT(126),
    CODEMP NUMBER(5),
    CODLOCAL NUMBER(10),
    CONTROLE VARCHAR2(100),
    NUNOTA NUMBER(10)
);
/* SCRIPT */
DECLARE
    COUNT_CODPROD NUMBER;
    COUNT_CUSTOPROD NUMBER;
    INSERIDOS NUMBER := 0;
    REPETIDOS NUMBER := 0;
    INEXISTENTES NUMBER := 0;
BEGIN
    FOR I IN (SELECT * FROM IMPORT_CUSTO)
    LOOP
        BEGIN
            SELECT COUNT(*)
              INTO COUNT_CODPROD
              FROM TGFPRO
             WHERE CODPROD = I.CODPROD;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            COUNT_CODPROD := 0;
        END;
        
        BEGIN
            SELECT COUNT(*)
              INTO COUNT_CUSTOPROD
              FROM TGFCUS
             WHERE CODPROD = I.CODPROD;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            COUNT_CUSTOPROD := 0;
        END;
        
        IF COUNT_CUSTOPROD > 0 THEN
            REPETIDOS := REPETIDOS + 1;
        END IF;
        
        IF COUNT_CODPROD = 0 THEN
            INEXISTENTES := INEXISTENTES + 1;
        END IF;
        
        IF COUNT_CODPROD > 0 AND COUNT_CUSTOPROD = 0 THEN
            INSERT INTO TGFCUS (CODPROD, DTATUAL, CUSVARIAVEL, CUSREP, CODEMP, 
                    CODLOCAL, NUNOTA)
                VALUES(I.CODPROD, I.DTATUAL, I.CUSVARIAVEL, I.CUSREP, I.CODEMP,
                        I.CODLOCAL, I.NUNOTA);
                        
            INSERIDOS := INSERIDOS + 1;
        END IF;    
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('INEXISTENTES: '|| INEXISTENTES);
    DBMS_OUTPUT.PUT_LINE('REPETIDOS: '|| REPETIDOS);
    DBMS_OUTPUT.PUT_LINE('INSERIDOS: '|| INSERIDOS);
    EXECUTE IMMEDIATE 'DELETE FROM IMPORT_CUSTO';
    EXECUTE IMMEDIATE 'DROP TABLE IMPORT_CUSTO';
END;
/