--CRIA TABELAS TEMPORÁRIAS
DECLARE
    IMPORTED NUMBER;
    TRATADO  NUMBER;
BEGIN
    SELECT COUNT(*) 
      INTO IMPORTED
      FROM ALL_TABLES 
     WHERE TABLE_NAME = 'IMPORT_TABLE' 
       AND STATUS = 'VALID';
       
    IF IMPORTED = 0 THEN   
        EXECUTE IMMEDIATE 
            'CREATE TABLE IMPORT_TABLE(
                CODPROD INT,
                CODEMP  INT,
                DETALHE VARCHAR2(4000)
            );';
    END IF;
    
    SELECT COUNT(*)
      INTO TRATADO
      FROM ALL_TABLES
     WHERE TABLE_NAME = 'LOCAL_TRATADO'
       AND STATUS = 'VALID';
    
    IF TRATADO = 0 THEN    
        EXECUTE IMMEDIATE 
            'CREATE TABLE LOCAL_TRATADO(
                CODPROD            INT,
                CODEMP             INT,
                DETALHE VARCHAR2(4000),
                CODIGOLOC          INT
            );';
    END IF;

END;
/
--INSERIR REGISTROS NA TABLEA IMPORT_LOCAL;
    /* *** */
--RODAR SCRIPT ABAIXO;    
DECLARE
    LOCAIS     VARCHAR2(4000);
    CODIGOLOC          NUMBER;
    CODLOC             NUMBER;
    CODPROD            NUMBER;
    SPLITER            NUMBER;
    PUTLINE            NUMBER;
BEGIN
    FOR I IN (SELECT CODPROD, DETALHE, CODEMP FROM IMPORT_LOCAL)
    LOOP
        IF I.CODEMP = 1 THEN
            FOR J IN (SELECT COLUMN_VALUE AS COL FROM TABLE(SPLIT(I.DETALHE, ' ')))
            LOOP
                BEGIN
                    SELECT LOCNVL
                      INTO CODIGOLOC
                      FROM AD_LOCPRODNVL
                     WHERE DESCRICAO = I.DETALHE;
                EXCEPTION WHEN NO_DATA_FOUND THEN
                    CODIGOLOC := NULL;
                END;
                
                INSERT INTO LOCAL_TRATADO
                    VALUES(I.CODPROD, I.CODEMP, J.COL, CODIGOLOC);
            END LOOP;
        ELSE
            BEGIN
                SELECT LOCNVL
                  INTO CODIGOLOC
                  FROM AD_LOCPRODNVL
                 WHERE DESCRICAO LIKE I.DETALHE;
            EXCEPTION WHEN NO_DATA_FOUND THEN
                CODIGOLOC := NULL;
            END;
            
            INSERT INTO LOCAL_TRATADO
                VALUES(I.CODPROD, I.CODEMP, I.DETALHE, CODIGOLOC);
        END IF;
    END LOOP;
    SELECT COUNT(*) INTO PUTLINE FROM LOCAL_TRATADO;
    DBMS_OUTPUT.PUT_LINE(PUTLINE);
END;
/
--LIMPA TABELA IMPORT_TABLE PARA PREVENIR ERROS 
DELETE FROM IMPORT_LOCAL;
--ANALISA PRODUTOS E LOCAIS QUE EXISTAM E INSERE NA TABELA OFICIAL DE LOCAIS
DECLARE
    CODILOC NUMBER;
    CODIPRO NUMBER;
    CODEMP  NUMBER;
BEGIN
    FOR I IN (SELECT * FROM LOCAL_TRATADO WHERE CODIGOLOC IS NOT NULL)
    LOOP
        BEGIN
            SELECT COUNT(CODPROD)
              INTO CODIPRO
              FROM TGFPRO
             WHERE CODPROD = I.CODPROD;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            CODIPRO := 0;
        END;

        IF CODIPRO != 0 THEN
            INSERT INTO AD_PRODCODNVL(LOCALPROD, CODPROD)
                VALUES(I.CODIGOLOC, I.CODPROD);
        END IF;
    END LOOP;
END;
/
--CONFERENCIA DE REGISTROS INSERIDOS/TOTAIS SE FOREM IGUAIS APAGA REGISTROS DA TABELA TEMPORARIA E EXCLUI TABELAS
DECLARE
    AB NUMBER;
    BB NUMBER;
BEGIN
    SELECT J.A, J.B 
      INTO AB, BB
      FROM
       (SELECT (SELECT COUNT(*) FROM LOCAL_TRATADO) AS A, 
           (SELECT COUNT(*) FROM AD_PRODCODNVL) AS B
              FROM DUAL)J;
    IF AB = BB THEN
        DBMS_OUTPUT.PUT_LINE('FEITO, LIMPANDO TUDO...');
        DELETE FROM LOCAL_TRATADO;
        EXECUTE IMMEDIATE 'DROP TABLE  LOCAL_TRATADO';
        EXECUTE IMMEDIATE 'DROP TABLE  IMPORT_LOCAL';
    END IF;
END;
/
--FIM
